trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: TerraformDeploy
    displayName: "Terraform deploy"
    jobs:
      - template: pipelines-templates/jobs/terraform-deploy.yml
        parameters:
          environment: "dev"
          azureServiceConnection: "ARM_SUBSCRIPTION"
  - stage: TerraformDestroy
    displayName: "Terraform destroy"
    jobs:
      - template: pipelines-templates/jobs/terraform-destroy.yml
        parameters:
          environment: "dev"
          azureServiceConnection: "ARM_SUBSCRIPTION"
