trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - "README.md"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: TerraformLintAndFormat
    displayName: "Terraform Lint and format"
    jobs:
      - template: pipelines-templates/jobs/terraform-lint.yml
        parameters:
          environment: "dev"
          azureServiceConnection: "ARM_SUBSCRIPTION"
  - stage: TerraformValidate
    displayName: "Terraform validate"
    jobs:
      - template: pipelines-templates/jobs/terraform-validate.yml
        parameters:
          environment: "dev"
          azureServiceConnection: "ARM_SUBSCRIPTION"
  - stage: TerraformPlan
    displayName: "Terraform plan"
    jobs:
      - template: pipelines-templates/jobs/terraform-plan.yml
        parameters:
          environment: "dev"
          azureServiceConnection: "ARM_SUBSCRIPTION"
