trigger:
  - "*"

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build Docker Image
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "crpmorosactivity4dev001"
              repository: "todolist"
              command: "build"
              Dockerfile: "**/app/Dockerfile"
              tags: "latest"

          - task: JFrogDocker@1
            inputs:
              command: "Scan"
              xrayConnection: "jfrog-xray"
              imageName: "crpmorosactivity4dev001.azurecr.io/todolist:latest"
              watchesSource: "none"
              licenses: false
              allowFailBuild: true
              threads: "3"
              skipLogin: false

          - task: Docker@2
            inputs:
              containerRegistry: "crpmorosactivity4dev001"
              repository: "todolist"
              command: "push"
              tags: "latest"

  - stage: Deploy
    displayName: Deploy to Web App
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy to WebApp
            inputs:
              azureSubscription: "ARM_SUBSCRIPTION"
              appName: "wa-activity4-dev-eastus"
              containers: "crpmorosactivity4dev001.azurecr.io/todolist:latest"
